#!/bin/mksh
echo -n "current_theme  "
first=true
for i in $(find /usr/share/slim/themes -type d); do
    if [[ $first == true ]]; then
        first=false
    else
        echo -n ','
    fi
    echo -n "${i##*/}"
done
echo
